### ISSUE TITLE
Adjust text

### ISSUE THREAD

**Issue by VVH** [zooniverse/annoTate#125] opened 2015-08-06 11:20 UTC
Text is very close to the edge of the page and looks a bit odd
![screen shot 2015-08-06 at 12 18 40](https://cloud.githubusercontent.com/assets/6482891/9110424/7887a480-3c35-11e5-9b2e-ecfe9e409e24.png)

**Comment by rogerhutchings** [comment] 2015-08-06 11:20
Dupe of #121

**Closed by rogerhutchings** 2015-08-06 11:20 UTC
