### ISSUE TITLE
Graphics off kilter in Safari

### ISSUE THREAD

**Issue by VVH** [zooniverse/AnnoTate#137] opened 2015-08-10 08:46 UTC
<img width="1216" alt="screen shot 2015-08-06 at 19 08 36" src="https://cloud.githubusercontent.com/assets/6482891/9164336/8525a2d4-3f44-11e5-820f-92f0ead9bc36.png">

**Comment by rogerhutchings** [comment] 2015-08-10 11:37
Duplicate of #136

**Closed by rogerhutchings** 2015-08-10 11:37 UTC
