### ISSUE TITLE
Image annotation tool starts drawing "late" on firefox

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/AnnoTate#173] opened 2015-09-02 10:43 UTC
When drawing a box with the image annotation tool the box does not start until the mouse has moved a small distance (~20 px or so) making it difficult to get the starting position of the box correct.  The tool works as expected in chrome.

Browser: Firefox 40.0.3
OS: Mac OS X 10.10.5

**Comment by rogerhutchings** [comment] 2015-09-02 14:02
Dupe of #128

**Closed by rogerhutchings** 2015-09-02 14:02 UTC
